package cn.sunline.oa;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class DailyReport {
    private String auditDirectorEmail;
    private String auditDirectorEmpCode;
    private String auditDirectorUsercode;
    private String auditDirectorWorkName;
    private String baseAddressCode;
    private String baseAddressName;
    private String bizSerialNo;
    private String bizTripFlag;
    private String businessLine;
    private String channelCode;
    private String coverType;
    private String createBy;
    private String createByName;
    private Date createTime;
    private String currentPage;
    private String dailyReportDataSoureCode;
    private String dailyReportDataSoureName;
    private String dailyReportId;
    private Object dailyReportIdList;
    private String dailyReportMajorTypeCode;
    private String dailyReportMajorTypeName;
    private String dailyReportStatus;
    private Object dailyReportStatusList;
    private String dailyReportStatusName;
    private String dailyReportTypeCode;
    private Object dailyReportTypeCodeList;
    private String dailyReportTypeName;
    private String dateStr;
    private String dateTypeCode;
    private Object dateTypeCodeList;
    private String dateTypeName;
    private Object dayTypeCode;
    private String dayTypeName;
    private String days;
    private Object defaultDate;
    private Object defaultEndDate;
    private Object defaultStartDate;
    private String deleteFlag;
    private String deptName1;
    private String deptName2;
    private String description;
    private Object directLeaderApprovalTime;
    private String empCode;
    private Object empCodeList;
    private String employeeBizOrgCode;
    private String employeeBizOrgName;
    private String employeeManageDeptCode;
    private String employeeManageDeptName;
    private Object endDate;
    private String endTimeline;
    private String exportType;
    private Date firstAuditingTime;
    private Date firstSubmitTime;
    private String generateMakeUpFillInFlag;
    private String groupCode;
    private String groupName;
    private Date lastTimesAuditingTime;
    private Date lastTimesSubmitTime;
    private String lastUpdateBy;
    private String lastUpdateByName;
    private Date lastUpdateTime;
    private String levelName;
    private String lockFlag;
    private String makeUpFillInFlag;
    private String managementDeptFullName;
    private String orderCode;
    private String orderName;
    private String pageSize;
    private String prodtResearchTypeCode;
    private String professionalLevelCode;
    private String projectBizOrgCode;
    private String projectBizOrgName;
    private String projectCode;
    private Object projectCodeList;
    private String projectManageDeptCode;
    private String projectManageDeptName;
    private String projectName;
    private String projectType;
    private Date reportDate;
    private Object returnTime;
    private String showReportType;
    private Object startDate;
    private String startTimeline;
    private String takeOfficeStatusCode;
    private String terminateLeaveBizSerialNo;
    private String timeline;
    private String timelineName;
    private String vacationTypeCode;
    private Integer weekId;
    private String weekName;
    private String workContent;
    private String workLocationCode;
    private String workLocationName;
    private String workName;
    private String ifTrip;
    private double attendanceDays;

}
